---

- name: application server
  hosts: all
  vars:
    run_scenario: "{{ scenario|default('deploy') }}"

  roles:
    - role: thefinn93.letsencrypt
      letsencrypt_webroot_path: /var/www/html
      letsencrypt_email: user@example.net
      letsencrypt_cert_domains:
        - test-staging.wfx.io
      when: run_scenario == "init"

    - role: roles/docker
      when: run_scenario == "init"

    - roles/prepare
    - roles/nginx
    - roles/app
