---
 - name: delete all sites enabled in nginx
   file: path=/etc/nginx/sites-enabled state=absent
   become: true

 - file: path=/etc/nginx/sites-enabled state=directory
   become: true

 - name: upload http vhost configuration
   template: src=templates/http.conf.j2 dest=/etc/nginx/conf.d/http.conf
   become: true

 - name: restart nginx
   service: name=nginx state=restarted
   become: true

 - name: add certbot ppa
   apt_repository: repo=ppa:certbot/certbot update_cache=yes
   become: true

 - name: install certbot
   apt: name=certbot
   become: true

 - name: obtain a letsencrypt certificate
   shell: /usr/bin/certbot certonly --webroot --email {{ admin_email }} --agree-tos --webroot-path=/var/www/html -d {{ inventory_hostname }};
   become: true

 - name: generate dhparams
   shell: /usr/bin/openssl dhparam -out /etc/ssl/certs/dhparams.pem 2048
   become: true

 - name: upload HTTPS vhost configuration
   template: src=templates/https.conf.j2 dest=/etc/nginx/conf.d/https.conf
   become: true

 - name: reload nginx again
   service: name=nginx state=reloaded
   become: true

 - name: add a certificate renewal cronjob
   cron: weekday=0 hour=5 minute=55 user=root job="/usr/bin/certbot renew --quiet --post-hook='service nginx reload'"
   become: true
