---
 - name: set hostname to inventory_hostname
   hostname: name={{ inventory_hostname }}
   become: true

 - name: adding group {{ system_group }}
   group: name={{ system_group }}
          state=present

 - name: allow {{ system_group }} group to have passwordless sudo
   lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ system_group }}'
    line: '%{{ system_group }} ALL=(ALL) NOPASSWD: ALL'

 - name: adding user {{ system_user }}
   user: name={{ system_user }}
         generate_ssh_key=yes
         group={{ system_user }}
         shell=/bin/bash
         groups=sudo
         append=yes

 - name: set authorized key for user ubuntu copying it from current user
   authorized_key:
    user: ubuntu
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

# In case of using password log-in.
#- name: copy the authorized_key
#  copy: src=~/.ssh/id_rsa.pub dest=/root/

#- name: Set authorized key took from file
#  authorized_key:
#    user: ubuntu
#    state: present
#   key: "{{ lookup('file', '/root/id_rsa.pub') }}"

 - name: update list of packages
   apt: update_cache=yes
   become: true

 - name: update the entire ubuntu system
   apt: upgrade=dist
   become: true

 - name: install the required packages
   apt: name={{item}} state=installed
   with_items:
   - build-essential
   - python3-pip
   - virtualenv
   - git
   - nginx
   - gcc-snapshot
   - libffi-dev
   - libssl-dev
   - libxml2-dev
   - libxslt1-dev
   - libjpeg8-dev
   - zlib1g-dev
   - libgdal-dev
   - gettext
   - redis-server
   - python-psycopg2
   - openssh-client
   become: true

