---
 - name: install postgresql
   apt: name=postgresql state=installed
   become: true

 - name: start postgresql
   service: name=postgresql state=started
   become: true

 - name: update pg_hba.conf file
   template: src=templates/pg_hba.conf.j2 dest=/etc/postgresql/{{ pg_version }}/{{ pg_cluster }}/pg_hba.conf owner={{ pg_admin_user }} group={{ pg_admin_user }} mode=0640
   become: true

 - name: add postgresql user "{{ system_user }}"
   postgresql_user: name={{ system_user }}
                    role_attr_flags=CREATEDB,LOGIN
   become: true 
   become_user: postgres

#- name: create postgresql database
#  postgresql_db: name={{ postgresql_dbname }}
#  become: true
#  become_user: postgres

 - name: create postgresql database
   shell: createdb {{ postgresql_dbname }}
   become: true
   become_user: "{{ system_user }}"

 - name: add postgresql role
   postgresql_user: db={{ postgresql_dbname }} name={{ postgresql_role }} priv=ALL
   become: true 
   become_user: postgres

 - name: add postgresql db "{{ system_user }}"
   postgresql_db: name={{ system_user }}
   become: true 
   become_user: postgres

 - name: restart postgresql server
   systemd: name=postgresql state=restarted daemon_reload=yes
   become: true
