---

- name: docker services from docker-compose.yml
  docker_service:
    project_src: "{{ playbook_dir }}/../../"
    files:
      - production.yml
    build: no
  register: output

- debug:
    var: output

#  - assert:
#    that:
#      - "web."
